#!/usr/bin/env node
/**
 * Generate docs/TOOLS.md from the running server's advertised tools, prompts,
 * resources, and resource templates — so the catalog can't drift from reality.
 *
 *   npm run build && node scripts/gen-catalog.mjs
 *   node scripts/gen-catalog.mjs --check   # exit 1 if docs/TOOLS.md is stale
 */

import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outPath = path.join(root, "docs", "TOOLS.md");
const check = process.argv.includes("--check");

// Surface the full group surface by enabling the gated raw group for the dump.
const transport = new StdioClientTransport({
  command: "node",
  args: ["dist/index.js"],
  cwd: root,
  env: { ...process.env, MCP_ENABLE_RAW: "true" },
  stderr: "ignore",
});
const client = new Client({ name: "gen-catalog", version: "1.0.0" });
await client.connect(transport);

const tools = (await client.listTools()).tools.sort((a, b) => a.name.localeCompare(b.name));
const prompts = (await client.listPrompts().catch(() => ({ prompts: [] }))).prompts;
const resources = (await client.listResources().catch(() => ({ resources: [] }))).resources;
const templates = (await client.listResourceTemplates().catch(() => ({ resourceTemplates: [] }))).resourceTemplates;
await client.close();

const lines = [];
lines.push("# Tool & resource catalog");
lines.push("");
lines.push("> Generated by `npm run docs:tools` from the running server. Do not edit by hand.");
lines.push("");
lines.push(`**${tools.length} tools**, ${prompts.length} prompts, ${resources.length} resources, ${templates.length} resource templates.`);
lines.push("");
lines.push("## Tools");
lines.push("");
lines.push("| Tool | Read-only | Description |");
lines.push("|---|---|---|");
for (const t of tools) {
  const ro = t.annotations?.readOnlyHint ? "✓" : "";
  const desc = (t.description ?? "").replace(/\s+/g, " ").replace(/\|/g, "\\|").slice(0, 160);
  lines.push(`| \`${t.name}\` | ${ro} | ${desc} |`);
}
lines.push("");
lines.push("## Prompts");
lines.push("");
for (const p of prompts) {
  const args = (p.arguments ?? []).map((a) => a.name + (a.required ? "" : "?")).join(", ");
  lines.push(`- \`${p.name}\`${args ? ` (${args})` : ""} — ${(p.description ?? "").replace(/\s+/g, " ")}`);
}
lines.push("");
lines.push("## Resources");
lines.push("");
for (const r of resources) lines.push(`- \`${r.uri}\` — ${(r.description ?? "").replace(/\s+/g, " ")}`);
for (const t of templates) lines.push(`- \`${t.uriTemplate}\` (template) — ${(t.description ?? "").replace(/\s+/g, " ")}`);
lines.push("");

const content = lines.join("\n");

if (check) {
  const existing = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : "";
  if (existing.trim() !== content.trim()) {
    console.error("docs/TOOLS.md is out of date. Run `npm run docs:tools` and commit the result.");
    process.exit(1);
  }
  console.log("docs/TOOLS.md is up to date.");
} else {
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, content, "utf8");
  console.log(`Wrote ${outPath} (${tools.length} tools).`);
}
process.exit(0);
